name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup

    strategy:
      matrix:
        test-type: [unit, integration]

    steps:
      - name: Run tests
        run: |
          if [ "${{ matrix.test-type }}" == "unit" ]; then
            npm run test:unit;
          elif [ "${{ matrix.test-type }}" == "integration" ]; then
            npm run test:integration;
          fi
